-- Supabase Database Schema for PriceIQ
-- Run this securely in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS products (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    keyword       TEXT NOT NULL,
    sku           TEXT,
    category      TEXT DEFAULT 'Umum',
    our_price     REAL DEFAULT 0,
    hpp           REAL DEFAULT 0,
    target_margin REAL DEFAULT 20,
    platforms     TEXT DEFAULT 'tokopedia,shopee',
    active        INTEGER DEFAULT 1,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    last_scraped  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS price_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    platform      TEXT NOT NULL,
    store_name    TEXT,
    store_url     TEXT,
    price         REAL NOT NULL,
    original_price REAL,
    discount_pct  REAL DEFAULT 0,
    rating        REAL,
    sold_count    INTEGER DEFAULT 0,
    badge         TEXT,
    scraped_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alerts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT REFERENCES products(id) ON DELETE CASCADE,
    type        TEXT DEFAULT 'info',
    title       TEXT NOT NULL,
    description TEXT,
    is_read     INTEGER DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_price_product ON price_history(product_id, scraped_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_read   ON alerts(is_read, created_at DESC);
